# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    pip install wheel
    pip install pytest pytest-azurepipelines
    pip install pytest-cov
  displayName: 'Install dependencies'

- script: |
    pytest --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml
  displayName: 'pytest'

- script: |
    bash $AGENT_BUILDDIRECTORY/s/install_scripts/create_packages.sh
  displayName: 'Create python wheels'

- task: CopyFiles@2
  inputs:
    sourceFolder: $(Agent.BuildDirectory)/s
    contents: |
      **/dist/**
    flattenFolders: True
    targetFolder: $(Build.ArtifactStagingDirectory)/whl

- task: CopyFiles@2
  inputs:
    sourceFolder: $(Build.Repository.LocalPath)/
    contents: |
      **/install_scripts/*.py
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: PythonWheels
